// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingSysApi.Contexts;

namespace TestingSysApi.Migrations.Test
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("TestingSysApi.Models.Test", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("answers");

                    b.Property<bool>("can_move_back");

                    b.Property<bool>("can_review");

                    b.Property<bool>("has_time");

                    b.Property<bool>("is_choice_random");

                    b.Property<int>("number_of_questions");

                    b.Property<int>("pass_questions_number");

                    b.Property<string>("questions");

                    b.Property<int>("time_in_seconds");

                    b.Property<int>("time_of_review");

                    b.HasKey("Id");

                    b.ToTable("Test");

                    b.HasData(
                        new { Id = 1L, answers = "", can_move_back = true, can_review = false, has_time = true, is_choice_random = true, number_of_questions = 3, pass_questions_number = 2, questions = "1#2#3#", time_in_seconds = 600, time_of_review = 0 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
