// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingSysApi.Contexts;

namespace TestingSysApi.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20200605163637_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("TestingSysApi.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("answer1");

                    b.Property<string>("answer2");

                    b.Property<string>("answer3");

                    b.Property<string>("answer4");

                    b.Property<string>("question");

                    b.Property<int>("true_answer");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new { Id = 1L, answer1 = "Paris", answer2 = "Rome", answer3 = "London", answer4 = "Berlin", question = "What's the capital of France?", true_answer = 1 },
                        new { Id = 2L, answer1 = "Paris", answer2 = "Rome", answer3 = "London", answer4 = "Berlin", question = "What's the capital of Italy?", true_answer = 2 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
